name: my_home Spring

# master 브랜치에 push, PR 이벤트 발생시 동작.
on:
  push:
    branches: [ "backend" ]
#   pull_request:
#     branches: [ "backend" ]

jobs:
  deploy: 
    runs-on: ubuntu-latest
    env:
      working-directory: /backend/my-home

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    
    # Spring Boot 어플리케이션 Build (1)
    - name: Spring Boot Build
      run: /backend/my-home/gradlew clean build --exclude-task test
    
    # Docker 이미지 Build (2)
    - name: docker image build
      run: docker build -t k0905sh/my_home .
    
    # DockerHub Login (3)
    - name: docker login 
      uses: docker/login-action@v2
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    # Docker Hub push (4)
    - name: docker Hub push
      run: docker push k0905sh/my_home
