name: my_home Spring

# master 브랜치에 push, PR 이벤트 발생시 동작.
on:
  push:
    branches: [ "master" ]
    paths: "backend/my-home/**" # backend/my-home/내부 코드 변경시만 실행
#   pull_request:
#     branches: [ "backend" ]
jobs:
  deploy: 
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name : Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: make application.yml
      # application-db.yml 파일 생성하기
      # Secrets에 저장한 값을 application.yml 파일에 쓰기
      run: | 
        touch ./backend/my-home/src/main/resources/application-db.yml 
        echo "${{ secrets.MY_HOME_DB }}" >> ./application-db.yml
      shell: bash
      
    # Spring Boot 어플리케이션 Build (1)
    - name: Spring Boot Build
      run: ./gradlew bootJar --exclude-task test
      working-directory: "./backend/my-home"
    
    # Docker 이미지 Build and push
    - name: web docker build and push
      run: |
        docker login -u ${{ secrets.DOCKERHUB_USERNAME }} -p ${{ secrets.DOCKERHUB_PASSWORD }}
        docker build -t ${{ secrets.MY_HOME_DOCKER_REPO }} .
        docker push ${{ secrets.MY_HOME_DOCKER_REPO }}
    

